name: Update Docker Hub Description

on:
  push:
    branches: [main]
    paths:
      - "README.md"
      - ".github/workflows/update-description.y*ml"

jobs:
  dockerHubDescription:
    name: Update Description on DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Evaluate the presence of secrets first
      - name: Check DockerHub Secrets
        id: check-secrets
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_TOKEN" ]; then
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has_secrets=false" >> $GITHUB_OUTPUT
          fi

      # Execute the update ONLY if the boolean output is true
      - name: Update dockerhub repo description
        if: steps.check-secrets.outputs.has_secrets == 'true'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/idrive-docker
          short-description: ${{ github.event.repository.description }}
